### ISSUE TITLE
I can’t find it

### ISSUE THREAD

**Issue by DeGraphics-Studios** [50thomatoes50/blender.io_mqo#2]
I have done everything that I was told to install ut I don't see the addon.
<img width="1680" alt="Screen Shot 2019-11-13 at 5 22 54 PM" src="https://user-images.githubusercontent.com/24575690/68809633-57da1000-063a-11ea-8d1a-072a11691850.png">

**Comment by 50thomatoes50** [comment]
you can find one release here.
The zip there is the standard Blender addon installation procedure.
https://github.com/50thomatoes50/blender.io_mqo/releases/tag/v0.2.0
