### ISSUE TITLE
Failed Imports

### ISSUE THREAD

**Issue by Brucien** [50thomatoes50/blender.io_mqo#3]
Failed on import for two different files, copied log below:

bpy.context.space_data.system_bookmarks_active = 1
bpy.context.space_data.params.directory = "C:\\Users\\cisco\\Desktop\\blender-mqo-master\\.github\\"
bpy.context.space_data.system_folders_active = 0
Modules Installed () from 'C:\\Program Files\\Blender Foundation\\Blender 2.81\\2.81\\scripts\\addons\\blender_mqo\\utils\\mqo_file.py' into 'C:\\Users\\cisco\\AppData\\Roaming\\Blender Foundation\\Blender\\2.81\\scripts\\addons'
bpy.data.window_managers["WinMan"].addon_support = {'TESTING'}
bpy.data.window_managers["WinMan"].addon_support = {'OFFICIAL'}
bpy.data.window_managers["WinMan"].addon_support = {'COMMUNITY'}
bpy.data.window_managers["WinMan"].addon_support = {'OFFICIAL'}
bpy.data.window_managers["WinMan"].addon_filter = 'All'
bpy.data.window_managers["WinMan"].addon_support = {'OFFICIAL', 'COMMUNITY'}
bpy.data.window_managers["WinMan"].addon_support = {'OFFICIAL', 'COMMUNITY', 'TESTING'}
Modules Installed () from 'C:\\Program Files\\Blender Foundation\\Blender 2.81\\2.81\\scripts\\addons\\utils\\addon_updater.py' into 'C:\\Users\\cisco\\AppData\\Roaming\\Blender Foundation\\Blender\\2.81\\scripts\\addons'
Modules Installed () from 'C:\\Program Files\\Blender Foundation\\Blender 2.81\\2.81\\scripts\\addons\\utils\\__init__.py' into 'C:\\Users\\cisco\\AppData\\Roaming\\Blender Foundation\\Blender\\2.81\\scripts\\addons'
Modules Installed () from 'C:\\Program Files\\Blender Foundation\\Blender 2.81\\2.81\\scripts\\addons\\utils\\mqo_file.py' into 'C:\\Users\\cisco\\AppData\\Roaming\\Blender Foundation\\Blender\\2.81\\scripts\\addons'
bpy.context.space_data.recent_folders_active = 2
Modules Installed () from 'C:\\Users\\cisco\\Desktop\\blender-mqo-master.zip' into 'C:\\Users\\cisco\\AppData\\Roaming\\Blender Foundation\\Blender\\2.81\\scripts\\addons'
bpy.data.window_managers["WinMan"].addon_filter = 'All'
bpy.data.window_managers["WinMan"].addon_filter = 'Import-Export'
bpy.context.space_data.system_folders_active = 1
.mqo import: Opening D:\Hobbies\3D Modelling\FFXIModelViewerEngV101\FFXI_Model_Viewer_-_Eng_v1-0-1\Model\ElvaanDrgAttack_AF1.mqo
.mqo import: Objects will be same size
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\scripts\addons\io_scene_mqo\__init__.py", line 209, in execute
    self.debug)
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\scripts\addons\io_scene_mqo\import_mqo.py", line 236, in import_mqo
    f_nb = int(words[1])
ValueError: invalid literal for int() with base 10: '346{'

location: <unknown location>:-1

bpy.context.space_data.recent_folders_active = 0
.mqo import: Opening D:\Hobbies\3D Modelling\FFXIModelViewerEngV101\FFXI_Model_Viewer_-_Eng_v1-0-1\Model\ElvaanDrgAttack_AF1.mqo
.mqo import: Objects will be same size
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\scripts\addons\io_scene_mqo\__init__.py", line 209, in execute
    self.debug)
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\scripts\addons\io_scene_mqo\import_mqo.py", line 236, in import_mqo
    f_nb = int(words[1])
ValueError: invalid literal for int() with base 10: '346{'

location: <unknown location>:-1

bpy.context.space_data.recent_folders_active = 1
bpy.context.space_data.recent_folders_active = 0
.mqo import: Opening D:\Hobbies\3D Modelling\FFXIModelViewerEngV101\FFXI_Model_Viewer_-_Eng_v1-0-1\Model\Judges Greaves_GM.mqo
.mqo import: Objects will be same size
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\scripts\addons\io_scene_mqo\__init__.py", line 209, in execute
    self.debug)
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\scripts\addons\io_scene_mqo\import_mqo.py", line 236, in import_mqo
    f_nb = int(words[1])
ValueError: invalid literal for int() with base 10: '132{'

location: <unknown location>:-1

**Comment by 50thomatoes50** [comment]
Could you upload the mqo file somewhere so i can have a look at it, please?
Does it import in Metasequoia 3D?

**Comment by sapper-trle** [comment]
Looks like MQO was built by custom software. I guess no space between '132' and '{' is problem.

ValueError: invalid literal for int() with base 10: '132{'

**Comment by Brucien** [comment]
yea, the MQO was built by custom software, a 3D model viewer for a game. It does open in Metasequoia. I can upload later this evening if @50thomatoes50 still wants it.

**Comment by sapper-trle** [comment]
If you cannot wait for fix you could open the MQO in a text editor like notepad and type a space between the number and the opening brace "{" in places where you have
face 132{
Make it face 132 { for each object. And tell author of custom software to maybe make change.

**Comment by 50thomatoes50** [comment]
this should fix the issue
https://github.com/50thomatoes50/blender.io_mqo/releases/tag/v0.2.1
